name: 🔒 Security Vulnerability
description:  Report security relevant issues
title: "[Security:] "
labels: ["enhancement", "triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security report!
  - type: textarea
    id: problem-area
    attributes:
      label: Problem
      description: Describe the security problem
    validations:
      required: true
